services:
  db:
    image: postgres:16-alpine
    container_name: emr-postgres
    environment:
      POSTGRES_DB: emr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: